platform :ios, '7.0'
#use_frameworks!个别需要用到它，比如reactiveCocoa

target 'JiDing' do
  pod 'AFNetworking', '~> 2.6'
  pod 'MWPhotoBrowser','~>2.1.2'
  pod 'MJExtension','~>3.0.13'
  pod 'UMengAnalytics','~>4.2.4'#标准SDK，含IDFA
  pod 'WechatOpenSDK','~>1.7.7'
  pod 'Reachability','~>3.2'
  pod 'IQKeyboardManager','~> 3.3.7'
  pod 'SDWebImage','~> 3.7.6'
  pod 'MJRefresh','~> 3.1.0'
  pod 'AMap3DMap','~> 4.0.0'
  pod 'AMapSearch','~> 4.0.0' #搜索服务SDK
  pod 'AMapLocation','~> 1.2.2' #定位SDK
  
  use_frameworks!
end
