platform :ios, '7.0'
#use_frameworks!个别需要用到它，比如reactiveCocoa

target 'JiDing' do
  pod 'AFNetworking', '~> 2.6'
  pod 'MWPhotoBrowser','~>2.1.2'
  pod 'MJExtension','~>3.0.13'
  pod 'UMengAnalytics','~>4.2.4'#标准SDK，含IDFA
  pod 'Reachability','~>3.2'
  pod 'IQKeyboardManager','~> 3.3.7'
  pod 'SDWebImage','~> 3.7.6'
  pod 'MJRefresh','~> 3.1.0'
  pod 'AMap3DMap','~> 4.0.0'
  pod 'AMapSearch','~> 4.0.0' #搜索服务SDK
  pod 'AMapLocation','~> 1.2.2' #定位SDK
  pod 'FDFullscreenPopGesture','~>1.1'
  pod 'ShareSDK3'# 主模块(必须)
  pod 'MOBFoundation'# Mob 公共库(必须) 如果同时集成SMSSDK iOS2.0:可看此注意事项：http://bbs.mob.com/thread-20051-1-1.html
  # 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
  pod 'ShareSDK3/ShareSDKPlatforms/QQ'
  pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
  pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
  use_frameworks!
end
